# Learning Numpy

In [1]:
import numpy as np

Numpy Integer

In [2]:
my_array=np.array([1,2,3,4,5])
print(my_array)
print(my_array.dtype)
print(my_array.dtype.itemsize)

[1 2 3 4 5]
int32
4


Numpy String

In [3]:
my_array=np.array(["Delhi","Mumbai","Kolkata"])
print(my_array)
print(my_array.dtype)
print(my_array.dtype.itemsize)

['Delhi' 'Mumbai' 'Kolkata']
<U7
28


Numpy Datetime

In [4]:
my_array=np.array(["2020-05-05","2023-07-07","2001-10-11"])
print(my_array)
print(my_array.dtype)
print(my_array.dtype.itemsize)

['2020-05-05' '2023-07-07' '2001-10-11']
<U10
40


Use of Numpy astype

In [5]:
my_array=my_array.astype("M")
print(my_array)
print(my_array.dtype)
print(my_array.dtype.itemsize)

['2020-05-05' '2023-07-07' '2001-10-11']
datetime64[D]
8


In [6]:
my_array=my_array.astype("S")
print(my_array)
print(my_array.dtype)
print(my_array.dtype.itemsize)

[b'2020-05-05' b'2023-07-07' b'2001-10-11']
|S28
28


Use of Numpy dtype while creating array

In [7]:
my_array=np.array(["2020-05-05","2023-07-07","2001-10-11"],dtype="M")
print(my_array)
print(my_array.dtype)
print(my_array.dtype.itemsize)

['2020-05-05' '2023-07-07' '2001-10-11']
datetime64[D]
8


Use of type function

In [8]:
nums_list=[1,2,3,4,5]
my_array=np.array(nums_list)
type(my_array)

numpy.ndarray

Use of Numpy shape

In [9]:
row1=[1,2,3,4]
row2=[1,2,3,4]
row3=[1,2,3,4]
# lis=[row1,row2,row3]
# lis
my_array=np.array([row1,row2,row3])
my_array.shape

(3, 4)

Use of Numpy arange function

In [10]:
my_array=np.arange(1,10)
my_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Use of Numpy arange function with stepsize

In [11]:
my_array=np.arange(1,30,2)
my_array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [12]:
Use of Numpy ones function

SyntaxError: invalid syntax (3346729662.py, line 1)

In [15]:
#1-D ones Array
my_array=np.ones(6,dtype="i")
my_array

array([1, 1, 1, 1, 1, 1], dtype=int32)

In [14]:
#2-D ones Array
my_array=np.ones([2,3],dtype="i")
my_array

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

Use of Numpy zeroes function

In [ ]:
#1-D zeroes Array
my_array=np.zeros(6,dtype="i")
my_array

In [ ]:
#2-D zeroes Array
my_array=np.zeros([2,3],dtype="i")
my_array

Use of Numpy eye function to create Identity Matrix

In [ ]:
my_array=np.eye(3,dtype="i")
my_array

Creation of Random numbers array using NumPy

In [16]:
#using random distribution
my_array=np.random.rand(2,3)
my_array

array([[0.29795712, 0.57806311, 0.90472703],
       [0.80858808, 0.99065445, 0.02919526]])

In [ ]:
#Using normal distribution
my_array=np.random.randn(2,3)
my_array

In [ ]:
#Generating random Integers
my_array=np.random.randint(5,50,5)
my_array


Use of Slicing and Indexing,Assignment

In [17]:
my_array=np.array([1,2,3,4,5])
my_array[1:4]

array([2, 3, 4])

In [ ]:
my_array=np.array([1,2,3,4,5])
my_array[2]=15
my_array

Use of Numpy Reshape


In [ ]:
# Reshaping from lower to higher dimensions
two_d_array = np.random.randint(1,20,size=(4,6))
three_d_array = np.reshape(two_d_array,(3,4,2))
print(two_d_array)
three_d_array

In [ ]:
#Reshaping from higher to lower dimensions
two_d_array = np.random.randint(1,20,size=(3,4,2))
three_d_array = np.reshape(two_d_array,(4,6))
print(two_d_array)
three_d_array

Use of Transpose function

In [ ]:
two_d_array = np.random.randint(1,20,size=(4,6))
transpose_matrix=np.transpose(two_d_array)
transpose_matrix

In [ ]:
array=np.array([1,2,3,4,5])
array[:-1]

Creating and Opening of CSV files and Reading from text files

In [ ]:
two_d_array = np.random.randint(1,20,size=(4,6))
two_d_array.tofile('File1.csv',",")
np.savetxt('File2.csv',two_d_array,delimiter=",")
new_array=np.genfromtxt('Text.txt',delimiter=",")
new_array

Benchmarking Performance between Numpy array and List

In [ ]:
two_d_array = np.random.randint(1,2000,size=(100,100))
two_d_array_2 = np.random.randint(1,2000,size=(100,100))
ls=list(two_d_array)
ls_2=list(two_d_array_2)
ls_2[1][1]

In [ ]:
import time

In [ ]:
#Time for Numpy arrays
start=time.time()
nm_result=two_d_array.copy()
result=np.matmul(two_d_array,two_d_array_2)
# for i in range(100):
#     for j in range(100):
#         for k in range(100):
#             nm_result[i][j]+=(ls[i][k]*ls[k][j])
end=time.time()
print(f"Numpy Time: {end-start}")
ls_result=ls.copy()

#Time for List
ls_start=time.time()
for i in range(100):
    for j in range(100):
        for k in range(100):
            ls_result[i][j]+=(ls[i][k]*ls[k][j])
ls_end=time.time()
print(f"List Time: {ls_end-ls_start}")
